packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@tailwindcss/oxide": true
  "@parcel/watcher": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  "@scarf/scarf": false
  msgpackr-extract: false
  workerd: false

overrides:
  mysql2: ^3.24.4
  deepmerge-ts: ^8.0.2
