export const ERROR_CODES = [
  'VALIDATION_FAILED',
  'UNAUTHENTICATED',
  'SESSION_EXPIRED',
  'FORBIDDEN',
  'NOT_FOUND',
  'INVALID_CREDENTIALS',
  'ACCOUNT_LOCKED',
  'ACCOUNT_SUSPENDED',
  'LOGIN_CHALLENGE_INVALID',
  'INVALID_TOTP_CODE',
  'TOTP_NOT_ENROLLED',
  'PASSWORD_CHANGE_NOT_REQUIRED',
  'PASSWORD_REUSED',
  'EMAIL_TAKEN',
  'CANNOT_CHANGE_OWN_ACCOUNT',
  'LAST_ACTIVE_ADMIN',
  'ROLE_NOT_ASSIGNABLE',
  'IPRESS_CODE_TAKEN',
  'FACILITY_INACTIVE',
  'ASSIGNMENT_ALREADY_ACTIVE',
  'ASSIGNMENT_NOT_ACTIVE',
  'VACCINE_CODE_TAKEN',
  'CATALOG_NOT_DRAFT',
  'CATALOG_EMPTY',
  'CATALOG_ENTRY_DUPLICATED',
  'CATALOG_RANGE_OVERLAP',
  'VALIDITY_NOT_AFTER_CURRENT',
  'VERSION_CONFLICT',
  'IDEMPOTENCY_KEY_REQUIRED',
  'IDEMPOTENCY_KEY_REUSED',
  'RATE_LIMITED',
  'SERVICE_UNAVAILABLE',
  'INTERNAL_ERROR',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  fields?: Record<string, string[]>;
}
